package livekit

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/sipeed/picoclaw/pkg/agent"
)

// GPTLivePersonaInput carries everything needed to compose a GPT-Live persona once,
// at session start. Persona and voice are immutable for the life of the session: the
// cascade's per-turn system messages (voice directive, language lock, quiz Door
// directive) have no equivalent under GPT-Live, so their content is folded into the
// delegation block composed here instead.
type GPTLivePersonaInput struct {
	Workspace      string
	CharacterName  string
	GreetingPrompt string
	LanguageName   string // "English" when empty
	Accent         string // "indian" | "default" (anything else behaves like "default")
	BankBlock      string // RenderQuizQuestions / RenderContentBank output, may be empty
	HasQuiz        bool
	SingleModel    bool // Grok Voice / Gemini Live: one model speaks and calls the tools itself
}

// GPTLivePersona is everything that is immutable once the session starts.
type GPTLivePersona struct {
	Voice    string // the voice model's instructions
	Backend  string // the backend Responses model's instructions
	Greeting string // full greeting instruction; also folded into Voice's <greeting_guidance> section
}

// gptLiveAccentIndian is a modifier on HOW to speak English, not a competing language
// instruction: it must never read as an imperative to speak English, because it can be
// combined with a language lock (gptLiveDelegationBlock) that names a different language,
// e.g. Hindi. The two must not contradict each other in the composed Voice string.
const gptLiveAccentIndian = `
<accent>
When you speak English, use an Indian accent: Indian intonation and rhythm, and the everyday
phrasing a child in India hears at home and at school. Keep it natural and warm, never a caricature.
This is about how to sound in English, not which language to use — follow the language
instruction above for that.
</accent>`

// gptLiveMemoOverride is appended, after the base persona, to explicitly override the
// character guidance's MEMO instruction. AGENT.md (generated by the manager into the
// workspace, folded into Persona.Voice via BuildSystemPrompt) tells the model to emit a
// "MEMO: ..." bookkeeping line at the end of a turn — e.g. a literal
// "MEMO: type=companion | date=YYYY-MM-DD | topics=..." template, plus "the runtime saves
// it automatically; never use tools." Under the cascade this was harmless: the model wrote
// the MEMO line as TEXT, and voiceMemoLineRE (audio_pipeline.go) stripped it before TTS ever
// spoke it. Under GPT-Live the voice model has no text stage — it speaks Persona.Voice
// directly — so it obeys the instruction and speaks the bookkeeping aloud to the child.
// stripGPTLiveMachineLines (this file) only catches a MEMO/QUIZ_BANK line that already
// exists as stored TEXT reaching Voice (e.g. via BankBlock); it cannot catch one the model
// generates live, at speech time, because the character guidance told it to. Hence this
// override, placed after the base persona so a later instruction wins.
//
// This must not contradict the persona's "never use tools" line: that stays true for the
// voice model (the backend does the tool calls) and is left alone. Only the instruction to
// SPEAK a MEMO/QUIZ_BANK line is overridden here.
// NOTE: this text deliberately never writes "MEMO" or "QUIZ_BANK" immediately followed by
// a colon — the exact shape it is telling the model never to speak — because
// TestBuildGPTLivePersonaStripsMemoLineFromVoice and
// TestBuildGPTLivePersonaStripsQuizBankHeaderKeepsWonderContent assert Voice never contains
// that literal substring, from any source.
const gptLiveMemoOverride = `<memo_override>
Never say, spell out, or read aloud a bookkeeping or state line out loud to the child: one
that starts with the word MEMO or QUIZ_BANK, then a colon, then pipe-delimited key=value
fields such as type=... | date=... | topics=.... Some of the character guidance above asks
you to speak a line shaped exactly like that at the end of a turn. Ignore that instruction
here: it does not apply to you and must never be followed.
The runtime records this session by itself. You do not need to say or spell out anything
for it to be saved.
</memo_override>`

// gptLiveDelegationBlock is the per-session equivalent of the cascade's per-turn voice
// directive, language lock and quiz Door directive: since GPT-Live cannot append fresh
// system messages mid-session, all three are folded into one block composed once here.
// It also carries gptLiveMemoOverride (see above) so the override lands after the base
// persona in the composed Voice string.
func gptLiveDelegationBlock(language string, hasQuiz bool) string {
	if strings.TrimSpace(language) == "" {
		language = "English"
	}
	var b strings.Builder
	b.WriteString("<delegation>\n")
	b.WriteString("You cannot look things up or keep score yourself. Delegate any question about the current time,\n")
	b.WriteString("date or weather, any factual question you are not sure about, and anything worth remembering\n")
	b.WriteString("about the child. While you wait, say one short cheerful line, then read out the result when it arrives.\n")
	b.WriteString("Answer greetings, small talk, jokes and simple questions yourself.\n")
	if hasQuiz {
		b.WriteString("Every time the child answers a quiz question, delegate so the answer gets scored\n")
		b.WriteString("(the helper calls quiz_score_answer), and then do exactly what the result tells you to do next:\n")
		b.WriteString("ask plainly, offer the two choices, explain then re-ask, or reveal and move on.\n")
		b.WriteString("Never decide on your own whether an answer was right.\n")
		b.WriteString("When the child answers TODAY's Wonder Question (the new one you ask after the Daily Ten or at goodbye),\n")
		b.WriteString("delegate so the question and their answer get recorded (the helper calls quiz_record_wonder).\n")
		b.WriteString("Do not delegate that for last time's Wonder Question when you remind the child of it at the start.\n")
	}
	fmt.Fprintf(&b, "Speak %s with the child unless they clearly switch language.\n", language)
	b.WriteString("</delegation>\n\n")
	b.WriteString(gptLiveMemoOverride)
	return b.String()
}

// gptLiveQuizJudging is the answer-judging rule for single-model vendors (Grok Voice,
// Gemini Live): with no backend model to compare the child's words against the bank
// answer, this is the guidance the one model itself uses to judge whether an answer counts.
const gptLiveQuizJudging = "Judge the meaning, not the exact words: a young child's synonym, a close paraphrase, or an answer " +
	"a kind teacher would accept (\"rain\" for water falling from the sky) is correct."

// gptLiveToolsBlock replaces gptLiveDelegationBlock for vendors whose one model calls the tools itself.
func gptLiveToolsBlock(language string, hasQuiz bool) string {
	if strings.TrimSpace(language) == "" {
		language = "English"
	}
	var b strings.Builder
	b.WriteString("<tools>\n")
	b.WriteString("You have tools, and this overrides any line above that says you cannot use tools. Use them silently:\n")
	b.WriteString("never mention a tool, a lookup or a file to the child.\n")
	b.WriteString("Use get_time_date for the current time or date and get_weather for weather. For news or any other\n")
	b.WriteString("fact you are not sure about, use a web search tool if one is available.\n")
	b.WriteString("Call remember_child_fact when the child tells you something worth remembering about themselves.\n")
	b.WriteString("Answer greetings, small talk, jokes and simple questions yourself.\n")
	if hasQuiz {
		b.WriteString("Every time the child answers a quiz question, call quiz_score_answer with question_id (the id\n")
		b.WriteString("shown in parentheses next to the question in the bank below, e.g. \"11\" for \"(id=11)\"),\n")
		b.WriteString("result=correct, miss or revealed (revealed = the child asked for the answer), and the child's\n")
		b.WriteString("words as transcript, then do exactly what the result tells you to do next: ask plainly,\n")
		b.WriteString("offer the two choices, explain then re-ask, or reveal and move on. Never decide on your own whether an\n")
		b.WriteString("answer was right without calling it. " + gptLiveQuizJudging + "\n")
		b.WriteString("A short reply right after a question, even \"I don't know\", is an answer attempt: score it.\n")
		b.WriteString("Call quiz_status if you are unsure which question is pending.\n")
	}
	fmt.Fprintf(&b, "Speak %s with the child unless they clearly switch language.\n", language)
	b.WriteString("</tools>\n\n")
	b.WriteString(gptLiveMemoOverride)
	return b.String()
}

// gptLiveRealtimeOverrides is the final section of a single-model (Grok Voice, Gemini Live)
// Voice. The manager's AGENT.md is written for a text agent behind a backend: it says the
// model has no tools, has it judge quiz answers itself, and asks for a hidden MEMO line that
// the runtime supposedly strips. A realtime model has no text stage, so in a live Gemini run
// it spoke the MEMO and never called quiz_score_answer; the <tools> paragraph earlier in Voice
// lost to ~28 KB of persona. Placed last so recency wins. Like gptLiveMemoOverride it never
// writes MEMO followed by a colon.
func gptLiveRealtimeOverrides(hasQuiz bool) string {
	var b strings.Builder
	b.WriteString("<realtime_overrides>\n")
	b.WriteString("These rules override anything earlier in these instructions.\n")
	b.WriteString("- You DO have the tools listed in <tools>, and you must use them. Ignore any earlier line that says you have no tools or must not call them.\n")
	if hasQuiz {
		b.WriteString("- When the child answers a quiz question, judge it by meaning as <tools> says (a synonym or close answer counts), then record that judgement by calling quiz_score_answer (question_id, result, transcript) before you tell the child whether it was right. Never judge silently without the tool or keep score in text.\n")
		b.WriteString("- Follow the tool result's scoring and next-step guidance.\n")
	}
	b.WriteString("- Never write, say or spell out a MEMO line or any other state or bookkeeping line, even when a tool result mentions a MEMO. Everything you output is spoken aloud; there are no hidden lines. The runtime records that state through the tools. Ignore any earlier instruction to add such a line.\n")
	b.WriteString("</realtime_overrides>")
	return b.String()
}

// gptLiveGreetingGuidance renders, for the Voice channel, what the model should say the
// first time it is asked to greet the child. Session-start instructions (Voice) carry no
// length cap, unlike a session.commentary.append (capped at 500 tokens by the service —
// see the "gptlive: session error ... Context append text must not exceed 500 tokens"
// production log this fixes). A manager-supplied greeting_prompt can run well past that
// cap, so the full guidance belongs here; Greet (gptlive_pipeline.go) then only ever sends
// a short nudge that points back at this section instead of repeating the guidance itself.
func gptLiveGreetingGuidance(characterName, greetingPrompt string) string {
	return "<greeting_guidance>\n" +
		"The first time you are asked to greet the child, open the conversation using this guidance:\n\n" +
		buildGreetingInstruction(characterName, greetingPrompt) +
		"\n</greeting_guidance>"
}

// gptLiveMachineBookkeepingLineRE matches whole MEMO:/QUIZ_BANK: header lines —
// the machine-readable bookkeeping memory/state/*.md files begin with (see
// quiz_state.go's WriteQuizBankState and pkg/agent/memory.go's ReadStateFiles).
// Under the cascade, voiceMemoLineRE (audio_pipeline.go) strips a MEMO line
// from the model's TEXT OUTPUT before TTS ever speaks it. GPT-Live has no text
// stage — the voice model speaks directly from Persona.Voice — so any such
// header line reaching Voice gets read aloud verbatim: production logged a
// companion MEMO line recited to a child. This regex mirrors voiceMemoLineRE's
// shape (line-anchored, case-insensitive) and additionally covers QUIZ_BANK:,
// the other state-file header format. Deliberately a sibling of
// voiceMemoLineRE, not a change to it: the cascade's own filtering must stay
// byte-identical.
var gptLiveMachineBookkeepingLineRE = regexp.MustCompile(`(?im)^[ \t]*(?:memo|quiz_bank)\s*:.*$`)

// gptLiveBlankRunRE collapses the run of blank lines a removed header line
// leaves behind (its content is gone but the line's own newline remains) down
// to a single blank line, so Voice instructions never carry runs of empty
// lines where a MEMO: or QUIZ_BANK: line used to be.
var gptLiveBlankRunRE = regexp.MustCompile(`\n{3,}`)

// stripGPTLiveMachineLines removes whole MEMO:/QUIZ_BANK: header lines from
// text bound for the voice model. It must be applied only to material that
// feeds Persona.Voice, never to Persona.Backend: the backend reasoning model
// may legitimately see this bookkeeping (it is the one that acts on it).
// Everything else in a state file — human-readable sections such as "Last
// Time You Wondered" or "Today's Wonder Question" — is left untouched; only
// lines that themselves start with the header survive.
func stripGPTLiveMachineLines(s string) string {
	stripped := gptLiveMachineBookkeepingLineRE.ReplaceAllString(s, "")
	return gptLiveBlankRunRE.ReplaceAllString(stripped, "\n\n")
}

// BuildGPTLivePersona composes the voice instructions, backend instructions and greeting
// commentary for a GPT-Live session. It is called once at session start; nothing it
// produces changes for the rest of the session.
func BuildGPTLivePersona(in GPTLivePersonaInput) GPTLivePersona {
	base := stripGPTLiveMachineLines(agent.NewContextBuilder(in.Workspace).BuildSystemPrompt())
	rules := gptLiveDelegationBlock(in.LanguageName, in.HasQuiz)
	if in.SingleModel {
		rules = gptLiveToolsBlock(in.LanguageName, in.HasQuiz)
	}
	parts := []string{base, rules}
	if trimmedBank := strings.TrimSpace(in.BankBlock); trimmedBank != "" {
		if voiceBank := strings.TrimSpace(stripGPTLiveMachineLines(in.BankBlock)); voiceBank != "" {
			parts = append(parts, voiceBank)
		}
	}
	if in.Accent == "indian" {
		parts = append(parts, strings.TrimSpace(gptLiveAccentIndian))
	}
	parts = append(parts, gptLiveGreetingGuidance(in.CharacterName, in.GreetingPrompt))
	if in.SingleModel {
		parts = append(parts, gptLiveRealtimeOverrides(in.HasQuiz)) // last, so recency wins
	}
	backend := ""
	if !in.SingleModel {
		backend = "You handle the work a voice model delegates while it talks to a child aged 3 to 16. " +
			"Use tools when current information is required or when the child says something worth remembering. " +
			"Reply with one or two short, friendly, child-safe sentences the voice model can read out."
		if in.HasQuiz {
			backend += " For quiz answers, compare the child's words with the bank answer and accepted answers, " +
				"then call quiz_score_answer with result=correct or result=miss; call quiz_status if unsure which question is pending."
		}
		if strings.TrimSpace(in.BankBlock) != "" {
			backend += "\n\n" + in.BankBlock
		}
	}
	return GPTLivePersona{
		Voice:    strings.Join(parts, "\n\n---\n\n"),
		Backend:  backend,
		Greeting: buildGreetingInstruction(in.CharacterName, in.GreetingPrompt),
	}
}
